--
-- DATABASE SETUP COMMANDS A&S
--

--
-- PARAMETERS
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

SET search_path = public, pg_catalog;

--
-- TABLES
--

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE admin (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email_address text NOT NULL,
    password text NOT NULL,
    last_update timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: soup_kitchen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE soup_kitchen (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL,
    review_list_id integer,
    cumulative_rate decimal(4, 2) NOT NULL,
    picture_url text NOT NULL,
    registered timestamptz DEFAULT now() NOT NULL,
    last_update timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.soup_kitchen OWNER TO postgres;

--
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE review (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review_text text NOT NULL,
    individual_rate decimal NOT NULL,
    last_update timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.review OWNER TO postgres;

--
-- FUNCTIONS
--

--
-- Name: last_updated(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION last_updated() RETURNS trigger
    AS $$
BEGIN
    NEW.last_update = now();
    RETURN NEW;
END $$
    LANGUAGE plpgsql;

ALTER FUNCTION public.last_updated() OWNER to postgres;

--
-- PRIMARY KEYS
--

--
-- Name: admin_pkey; Type: PK_CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);
    
--
-- Name: soup_kitchen_pkey; Type: PK_CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY soup_kitchen
    ADD CONSTRAINT soup_kitchen_pkey PRIMARY KEY (id);
    
-- 
-- Name: review_pkey; Type: PK_CONSTRAINT; Schema: public; Owner: postgres
-- 

ALTER TABLE ONLY review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);
    
--
-- FOREIGN KEYS
--

--
-- Name soup_kitchen_review_fkey; Type: FK_CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY soup_kitchen
    ADD CONSTRAINT soup_kitchen_review_fkey FOREIGN KEY (review_list_id) REFERENCES review(id) ON UPDATE CASCADE ON DELETE RESTRICT;
    
--
-- TRIGGERS
--

--
-- Name: last_updated; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER last_updated
    BEFORE UPDATE ON admin
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
    

--
-- Name: last_updated; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER last_updated
    BEFORE UPDATE ON soup_kitchen
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();
    
--
-- Name: last_updated; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER last_updated
    BEFORE UPDATE ON review
    FOR EACH ROW
    EXECUTE PROCEDURE last_updated();